title: Aldus Manutius Digitized and Transcribed
description: Digitial transcriptions of the Aldine collection held in the Special Collections and Rare Books at Simon Fraser University
show_downloads: true
google_analytics:
theme: minima
