title: Aldis Manutius Decameron
description: Digitial edition of the Aldine collection held in the Special Collections and Rare Books at Simon Fraser University
show_downloads: true
google_analytics:
theme: jekyll-theme-tactile
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme
